DROP TABLE IF EXISTS "Regions" CASCADE;

DROP TABLE IF EXISTS "Areas" CASCADE;

DROP TABLE IF EXISTS "ClassLanguage" CASCADE;

DROP TABLE IF EXISTS "ClassProfile" CASCADE;

DROP TABLE IF EXISTS "TestDPA" CASCADE;

DROP TABLE IF EXISTS "RegistrationType" CASCADE;

DROP TABLE IF EXISTS "Genders" CASCADE;

DROP TABLE IF EXISTS "TerritoriesType" CASCADE;

DROP TABLE IF EXISTS "Territories" CASCADE;

DROP TABLE IF EXISTS "School" CASCADE;

DROP TABLE IF EXISTS "TestStatus" CASCADE;

DROP TABLE IF EXISTS "TestSubject" CASCADE;

DROP TABLE IF EXISTS "TestYear" CASCADE;

DROP TABLE IF EXISTS "TestLanguage" CASCADE;

DROP TABLE IF EXISTS "Student" CASCADE;

DROP TABLE IF EXISTS "ZnoTest" CASCADE;